import type { Product } from "./types"

export const allProducts: Product[] = [
  // Men's Products (10 products)
  {
    id: "classic-black-tee-men",
    name: "Classic Black Tee",
    price: 350.0,
    image: "/images/black-tshirt.jpeg",
    description: "Soft organic cotton tee for everyday comfort and timeless style.",
    category: "Men",
    images: [
      "/images/black-tshirt.jpeg",
      "/images/black-barco-tshirt.jpeg",
      "/images/white-tshirt.jpeg",
      "/images/white-tshirt-alt.jpeg",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "White", hex: "#FFFFFF" },
      { name: "Cream", hex: "#F5F5DC" },
    ],
    material: "100% Organic Cotton",
    careInstructions: "Machine wash cold, tumble dry low. Do not bleach. Iron on low heat.",
    fabric: ["Cotton"],
    model3D: "/models/tshirt.glb", // Placeholder GLB
  },
  {
    id: "branded-black-tee-men",
    name: "Branded Black Tee",
    price: 420.0,
    image: "/images/black-barco-tshirt.jpeg",
    description: "Premium black tee with subtle Atenoir branding for a sophisticated casual look.",
    category: "Men",
    images: ["/images/black-barco-tshirt.jpeg", "/images/black-tshirt.jpeg", "/images/white-tshirt.jpeg"],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "White", hex: "#FFFFFF" },
    ],
    material: "95% Cotton, 5% Spandex",
    careInstructions: "Machine wash cold, inside out. Tumble dry low.",
    fabric: ["Cotton", "Spandex"],
    model3D: "/models/tshirt.glb", // Placeholder GLB
  },
  {
    id: "vibrant-yellow-button-up-men",
    name: "Vibrant Yellow Button-Up",
    price: 450.0,
    image: "/images/yellow-button-up.jpeg",
    description: "A stylish yellow button-up shirt, perfect for adding a fresh pop of color to your wardrobe.",
    category: "Men",
    images: ["/images/yellow-button-up.jpeg", "/images/yellow-long-sleeve.jpeg"],
    sizes: ["M", "L", "XL"],
    colors: [
      { name: "Yellow", hex: "#FFD700" },
      { name: "White", hex: "#FFFFFF" },
    ],
    material: "70% Cotton, 30% Linen",
    careInstructions: "Machine wash cold, hang dry.",
    fabric: ["Cotton", "Linen"],
    model3D: "/models/shirt.glb", // Placeholder GLB
  },
  {
    id: "yellow-long-sleeve-men",
    name: "Yellow Long Sleeve",
    price: 490.0,
    image: "/images/yellow-long-sleeve.jpeg",
    description: "Comfortable long-sleeve shirt in a soft yellow, ideal for layering or cooler days.",
    category: "Men",
    images: ["/images/yellow-long-sleeve.jpeg", "/images/yellow-button-up.jpeg"],
    sizes: ["M", "L", "XL"],
    colors: [
      { name: "Yellow", hex: "#FFD700" },
      { name: "Cream", hex: "#F5F5DC" },
    ],
    material: "60% Cotton, 40% Modal",
    careInstructions: "Machine wash cold, lay flat to dry.",
    fabric: ["Cotton", "Modal"],
    model3D: "/models/long-sleeve.glb", // Placeholder GLB
  },
  {
    id: "mens-slim-fit-jeans",
    name: "Men's Slim Fit Jeans",
    price: 480.0,
    image: "/placeholder.svg?height=400&width=300",
    description: "Modern slim-fit jeans crafted from premium denim for comfort and style.",
    category: "Men",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    sizes: ["28", "30", "32", "34", "36"],
    colors: [
      { name: "Dark Blue", hex: "#00008B" },
      { name: "Black", hex: "#000000" },
    ],
    material: "98% Cotton, 2% Elastane",
    careInstructions: "Machine wash cold, inside out.",
    fabric: ["Denim", "Elastane"],
    model3D: "/models/jeans.glb", // Placeholder GLB
  },
  {
    id: "mens-classic-polo",
    name: "Men's Classic Polo",
    price: 390.0,
    image: "/placeholder.svg?height=300&width=300",
    description: "A timeless classic polo shirt, perfect for smart-casual occasions.",
    category: "Men",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Navy", hex: "#000080" },
      { name: "White", hex: "#FFFFFF" },
      { name: "Burgundy", hex: "#800020" },
    ],
    material: "100% Pique Cotton",
    careInstructions: "Machine wash warm, tumble dry medium.",
    fabric: ["Cotton"],
    model3D: "/models/polo.glb", // Placeholder GLB
  },
  {
    id: "mens-leather-jacket",
    name: "Men's Leather Jacket",
    price: 499.0,
    image: "/placeholder.svg?height=450&width=400",
    description: "Luxurious genuine leather jacket, a statement piece for any wardrobe.",
    category: "Men",
    images: ["/placeholder.svg?height=450&width=400", "/placeholder.svg?height=450&width=400"],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Brown", hex: "#A52A2A" },
    ],
    material: "100% Lambskin Leather",
    careInstructions: "Professional leather clean only.",
    fabric: ["Leather"],
    model3D: "/models/jacket.glb", // Placeholder GLB
  },
  {
    id: "mens-casual-hoodie",
    name: "Men's Casual Hoodie",
    price: 410.0,
    image: "/placeholder.svg?height=350&width=350",
    description: "Comfortable and stylish hoodie, perfect for relaxed days.",
    category: "Men",
    images: ["/placeholder.svg?height=350&width=350", "/placeholder.svg?height=350&width=350"],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Grey", hex: "#808080" },
      { name: "Navy", hex: "#000080" },
    ],
    material: "80% Cotton, 20% Polyester",
    careInstructions: "Machine wash cold, tumble dry low.",
    fabric: ["Cotton", "Fleece"],
    model3D: "/models/hoodie.glb", // Placeholder GLB
  },
  {
    id: "mens-chinos",
    name: "Men's Classic Chinos",
    price: 370.0,
    image: "/placeholder.svg?height=400&width=300",
    description: "Versatile chinos offering a smart yet comfortable fit for any occasion.",
    category: "Men",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    sizes: ["28", "30", "32", "34", "36"],
    colors: [
      { name: "Khaki", hex: "#C3B091" },
      { name: "Navy", hex: "#000080" },
      { name: "Olive", hex: "#808000" },
    ],
    material: "97% Cotton, 3% Spandex",
    careInstructions: "Machine wash cold, iron low.",
    fabric: ["Cotton", "Spandex"],
    model3D: "/models/trousers.glb", // Placeholder GLB
  },
  {
    id: "mens-graphic-tshirt",
    name: "Men's Abstract Graphic Tee",
    price: 330.0,
    image: "/placeholder.svg?height=300&width=300",
    description: "Soft cotton tee featuring a unique abstract graphic print.",
    category: "Men",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "White", hex: "#FFFFFF" },
    ],
    material: "100% Cotton",
    careInstructions: "Machine wash cold, inside out.",
    fabric: ["Cotton"],
    model3D: "/models/tshirt.glb", // Placeholder GLB
  },

  // Women's Products (10 products)
  {
    id: "champagne-short-sleeve-women",
    name: "Champagne Short Sleeve",
    price: 480.0,
    image: "/images/champagne-shirt.jpeg",
    description: "Elegant short-sleeve shirt in a luxurious champagne hue, perfect for sophisticated ensembles.",
    category: "Women",
    images: ["/images/champagne-shirt.jpeg", "/images/gold-shirt.jpeg"],
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: "Champagne", hex: "#F7E7CE" },
      { name: "Gold", hex: "#FFD700" },
    ],
    material: "100% Silk",
    careInstructions: "Dry clean only.",
    fabric: ["Silk"],
    model3D: "/models/blouse.glb", // Placeholder GLB
  },
  {
    id: "crisp-white-tee-women",
    name: "Crisp White Tee",
    price: 380.0,
    image: "/images/white-tshirt.jpeg",
    description: "An essential white tee for versatile styling, offering comfort and a clean aesthetic.",
    category: "Women",
    images: ["/images/white-tshirt.jpeg", "/images/white-tshirt-alt.jpeg", "/images/black-tshirt.jpeg"],
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#000000" },
    ],
    material: "100% Supima Cotton",
    careInstructions: "Machine wash cold, tumble dry low.",
    fabric: ["Cotton"],
    model3D: "/models/tshirt.glb", // Placeholder GLB
  },
  {
    id: "white-logo-tee-women",
    name: "White Logo Tee",
    price: 410.0,
    image: "/images/white-tshirt-alt.jpeg",
    description: "Classic white tee with a minimalist logo, blending comfort with subtle brand recognition.",
    category: "Women",
    images: ["/images/white-tshirt-alt.jpeg", "/images/white-tshirt.jpeg"],
    sizes: ["S", "M", "L"],
    colors: [{ name: "White", hex: "#FFFFFF" }],
    material: "90% Cotton, 10% Polyester",
    careInstructions: "Machine wash cold, gentle cycle.",
    fabric: ["Cotton", "Polyester"],
    model3D: "/models/tshirt.glb", // Placeholder GLB
  },
  {
    id: "gold-shirt-women",
    name: "Radiant Gold Blouse",
    price: 500.0,
    image: "/images/gold-shirt.jpeg",
    description: "A stunning gold blouse for special occasions, designed to make a statement.",
    category: "Women",
    images: ["/images/gold-shirt.jpeg", "/images/champagne-shirt.jpeg"],
    sizes: ["XS", "S", "M"],
    colors: [
      { name: "Gold", hex: "#FFD700" },
      { name: "Champagne", hex: "#F7E7CE" },
    ],
    material: "Polyester Blend",
    careInstructions: "Hand wash cold, hang dry.",
    fabric: ["Polyester"],
    model3D: "/models/blouse.glb", // Placeholder GLB
  },
  {
    id: "womens-high-waisted-skirt",
    name: "Women's High-Waisted Skirt",
    price: 430.0,
    image: "/placeholder.svg?height=400&width=300",
    description: "Elegant high-waisted skirt, perfect for a sophisticated and flattering silhouette.",
    category: "Women",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Navy", hex: "#000080" },
    ],
    material: "60% Viscose, 35% Nylon, 5% Spandex",
    careInstructions: "Dry clean recommended.",
    fabric: ["Viscose", "Nylon", "Spandex"],
    model3D: "/models/skirt.glb", // Placeholder GLB
  },
  {
    id: "womens-silk-blouse",
    name: "Women's Silk Blouse",
    price: 490.0,
    image: "/placeholder.svg?height=350&width=350",
    description: "Luxurious silk blouse, soft to the touch and effortlessly chic.",
    category: "Women",
    images: ["/placeholder.svg?height=350&width=350", "/placeholder.svg?height=350&width=350"],
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: "Ivory", hex: "#FFFFF0" },
      { name: "Blush", hex: "#FFC0CB" },
    ],
    material: "100% Mulberry Silk",
    careInstructions: "Hand wash cold, lay flat to dry.",
    fabric: ["Silk"],
    model3D: "/models/blouse.glb", // Placeholder GLB
  },
  {
    id: "womens-elegant-dress",
    name: "Women's Elegant Midi Dress",
    price: 470.0,
    image: "/placeholder.svg?height=450&width=300",
    description: "A beautifully draped midi dress, perfect for evening events or sophisticated daytime wear.",
    category: "Women",
    images: ["/placeholder.svg?height=450&width=300", "/placeholder.svg?height=450&width=300"],
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: "Emerald Green", hex: "#50C878" },
      { name: "Black", hex: "#000000" },
    ],
    material: "95% Polyester, 5% Spandex",
    careInstructions: "Machine wash cold, hang dry.",
    fabric: ["Polyester", "Spandex"],
    model3D: "/models/dress.glb", // Placeholder GLB
  },
  {
    id: "womens-knit-sweater",
    name: "Women's Cozy Knit Sweater",
    price: 460.0,
    image: "/placeholder.svg?height=350&width=350",
    description: "Soft and warm knit sweater, ideal for comfort and style in cooler weather.",
    category: "Women",
    images: ["/placeholder.svg?height=350&width=350", "/placeholder.svg?height=350&width=350"],
    sizes: ["S", "M", "L"],
    colors: [
      { name: "Beige", hex: "#F5F5DC" },
      { name: "Charcoal", hex: "#36454F" },
    ],
    material: "50% Wool, 50% Acrylic",
    careInstructions: "Hand wash cold, lay flat to dry.",
    fabric: ["Wool", "Acrylic"],
    model3D: "/models/sweater.glb", // Placeholder GLB
  },
  {
    id: "womens-wide-leg-trousers",
    name: "Women's Wide-Leg Trousers",
    price: 440.0,
    image: "/placeholder.svg?height=400&width=300",
    description: "Fashionable wide-leg trousers offering a relaxed fit and elegant drape.",
    category: "Women",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: "Cream", hex: "#F5F5DC" },
      { name: "Black", hex: "#000000" },
    ],
    material: "100% Linen",
    careInstructions: "Machine wash cold, gentle cycle.",
    fabric: ["Linen"],
    model3D: "/models/trousers.glb", // Placeholder GLB
  },
  {
    id: "womens-denim-jacket",
    name: "Women's Classic Denim Jacket",
    price: 495.0,
    image: "/placeholder.svg?height=350&width=350",
    description: "A timeless denim jacket, perfect for layering and adding a casual-chic touch.",
    category: "Women",
    images: ["/placeholder.svg?height=350&width=350", "/placeholder.svg?height=350&width=350"],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Blue Denim", hex: "#4682B4" },
      { name: "Black Denim", hex: "#2F4F4F" },
    ],
    material: "100% Cotton Denim",
    careInstructions: "Machine wash cold, inside out.",
    fabric: ["Denim"],
    model3D: "/models/jacket.glb", // Placeholder GLB
  },

  // Kids' Products (10 products)
  {
    id: "sunny-yellow-tee-kids",
    name: "Sunny Yellow Tee",
    price: 320.0,
    image: "/images/yellow-tshirt.jpeg",
    description: "Bright yellow tee for a cheerful vibe, made with soft, breathable fabric for kids.",
    category: "Kids",
    images: ["/images/yellow-tshirt.jpeg", "/images/white-tshirt.jpeg"],
    sizes: ["2T", "3T", "4T", "5T"],
    colors: [
      { name: "Yellow", hex: "#FFD700" },
      { name: "White", hex: "#FFFFFF" },
    ],
    material: "100% Organic Cotton",
    careInstructions: "Machine wash warm, tumble dry low.",
    fabric: ["Cotton"],
    model3D: "/models/tshirt-kids.glb", // Placeholder GLB
  },
  {
    id: "kids-graphic-tee-kids",
    name: "Kids Graphic Tee",
    price: 250.0,
    image: "/placeholder.svg?height=300&width=300", // Placeholder for a kids' specific image
    description: "Fun and comfortable graphic tee for kids, featuring playful designs.",
    category: "Kids",
    images: ["/placeholder.svg?height=300&width=300", "/images/yellow-tshirt.jpeg"],
    sizes: ["2T", "3T", "4T", "5T", "Youth S", "Youth M"],
    colors: [
      { name: "Blue", hex: "#0000FF" },
      { name: "Red", hex: "#FF0000" },
    ],
    material: "100% Cotton",
    careInstructions: "Machine wash cold, tumble dry low.",
    fabric: ["Cotton"],
    model3D: "/models/tshirt-kids.glb", // Placeholder GLB
  },
  {
    id: "kids-denim-overalls",
    name: "Kids' Denim Overalls",
    price: 400.0,
    image: "/placeholder.svg?height=350&width=300",
    description: "Durable and cute denim overalls for active kids, perfect for play.",
    category: "Kids",
    images: ["/placeholder.svg?height=350&width=300", "/placeholder.svg?height=350&width=300"],
    sizes: ["2T", "3T", "4T", "5T"],
    colors: [{ name: "Blue Denim", hex: "#4682B4" }],
    material: "100% Cotton Denim",
    careInstructions: "Machine wash warm, tumble dry low.",
    fabric: ["Denim"],
    model3D: "/models/overalls-kids.glb", // Placeholder GLB
  },
  {
    id: "kids-striped-hoodie",
    name: "Kids' Striped Hoodie",
    price: 380.0,
    image: "/placeholder.svg?height=300&width=300",
    description: "Cozy striped hoodie for kids, offering warmth and a playful style.",
    category: "Kids",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
    sizes: ["2T", "3T", "4T", "5T", "Youth S"],
    colors: [
      { name: "Navy/White", hex: "#000080" },
      { name: "Red/White", hex: "#FF0000" },
    ],
    material: "60% Cotton, 40% Polyester Fleece",
    careInstructions: "Machine wash cold, tumble dry low.",
    fabric: ["Cotton", "Fleece"],
    model3D: "/models/hoodie-kids.glb", // Placeholder GLB
  },
  {
    id: "kids-playful-dress",
    name: "Kids' Playful Floral Dress",
    price: 450.0,
    image: "/placeholder.svg?height=350&width=300",
    description: "A charming floral dress for girls, perfect for special occasions or everyday fun.",
    category: "Kids",
    images: ["/placeholder.svg?height=350&width=300", "/placeholder.svg?height=350&width=300"],
    sizes: ["2T", "3T", "4T", "5T"],
    colors: [
      { name: "Pink Floral", hex: "#FFC0CB" },
      { name: "Blue Floral", hex: "#ADD8E6" },
    ],
    material: "100% Cotton",
    careInstructions: "Machine wash cold, hang dry.",
    fabric: ["Cotton"],
    model3D: "/models/dress-kids.glb", // Placeholder GLB
  },
  {
    id: "kids-adventure-shorts",
    name: "Kids' Adventure Shorts",
    price: 280.0,
    image: "/placeholder.svg?height=300&width=300",
    description: "Durable and comfortable shorts for kids' outdoor adventures.",
    category: "Kids",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
    sizes: ["2T", "3T", "4T", "5T", "Youth S"],
    colors: [
      { name: "Khaki", hex: "#C3B091" },
      { name: "Navy", hex: "#000080" },
    ],
    material: "97% Cotton, 3% Spandex",
    careInstructions: "Machine wash warm, tumble dry low.",
    fabric: ["Cotton", "Spandex"],
    model3D: "/models/shorts-kids.glb", // Placeholder GLB
  },
  {
    id: "kids-animal-print-tee",
    name: "Kids' Animal Print Tee",
    price: 290.0,
    image: "/placeholder.svg?height=300&width=300",
    description: "Fun animal print tee, soft and breathable for everyday wear.",
    category: "Kids",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
    sizes: ["2T", "3T", "4T", "5T"],
    colors: [
      { name: "Lion Print", hex: "#FFA500" },
      { name: "Zebra Print", hex: "#FFFFFF" },
    ],
    material: "100% Cotton",
    careInstructions: "Machine wash cold, inside out.",
    fabric: ["Cotton"],
    model3D: "/models/tshirt-kids.glb", // Placeholder GLB
  },
  {
    id: "kids-cozy-sweatpants",
    name: "Kids' Cozy Sweatpants",
    price: 340.0,
    image: "/placeholder.svg?height=300&width=300",
    description: "Ultra-soft sweatpants for ultimate comfort during play or relaxation.",
    category: "Kids",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
    sizes: ["2T", "3T", "4T", "5T", "Youth S"],
    colors: [
      { name: "Grey", hex: "#808080" },
      { name: "Black", hex: "#000000" },
    ],
    material: "80% Cotton, 20% Polyester Fleece",
    careInstructions: "Machine wash warm, tumble dry low.",
    fabric: ["Cotton", "Fleece"],
    model3D: "/models/sweatpants-kids.glb", // Placeholder GLB
  },
  {
    id: "kids-rain-jacket",
    name: "Kids' Lightweight Rain Jacket",
    price: 490.0,
    image: "/placeholder.svg?height=350&width=350",
    description: "Water-resistant jacket to keep kids dry and comfortable on rainy days.",
    category: "Kids",
    images: ["/placeholder.svg?height=350&width=350", "/placeholder.svg?height=350&width=350"],
    sizes: ["2T", "3T", "4T", "5T", "Youth S"],
    colors: [
      { name: "Blue", hex: "#0000FF" },
      { name: "Yellow", hex: "#FFD700" },
    ],
    material: "100% Polyester",
    careInstructions: "Machine wash cold, hang dry.",
    fabric: ["Polyester"],
    model3D: "/models/jacket-kids.glb", // Placeholder GLB
  },
  {
    id: "kids-patterned-leggings",
    name: "Kids' Patterned Leggings",
    price: 270.0,
    image: "/placeholder.svg?height=300&width=300",
    description: "Stretchy and fun patterned leggings for everyday wear and active play.",
    category: "Kids",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
    sizes: ["2T", "3T", "4T", "5T"],
    colors: [
      { name: "Stars", hex: "#FFFFFF" },
      { name: "Stripes", hex: "#000000" },
    ],
    material: "95% Cotton, 5% Spandex",
    careInstructions: "Machine wash cold, tumble dry low.",
    fabric: ["Cotton", "Spandex"],
    model3D: "/models/leggings-kids.glb", // Placeholder GLB
  },

  // Shirts Products (10 products)
  {
    id: "classic-oxford-shirt",
    name: "Classic Oxford Shirt",
    price: 450.0,
    image: "/placeholder.svg?height=350&width=300",
    description: "A timeless Oxford shirt, perfect for both casual and formal settings.",
    category: "Shirts",
    images: ["/placeholder.svg?height=350&width=300", "/placeholder.svg?height=350&width=300"],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Light Blue", hex: "#ADD8E6" },
    ],
    material: "100% Cotton",
    careInstructions: "Machine wash warm, tumble dry low.",
    fabric: ["Cotton"],
    model3D: "/models/shirt.glb",
  },
  {
    id: "linen-blend-shirt",
    name: "Linen Blend Casual Shirt",
    price: 480.0,
    image: "/placeholder.svg?height=350&width=300",
    description: "Lightweight and breathable linen blend shirt, ideal for warm weather.",
    category: "Shirts",
    images: ["/placeholder.svg?height=350&width=300", "/placeholder.svg?height=350&width=300"],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Beige", hex: "#F5F5DC" },
      { name: "Navy", hex: "#000080" },
    ],
    material: "70% Linen, 30% Cotton",
    careInstructions: "Machine wash cold, hang dry.",
    fabric: ["Linen", "Cotton"],
    model3D: "/models/shirt.glb",
  },
  {
    id: "silk-button-up",
    name: "Luxurious Silk Button-Up",
    price: 620.0,
    image: "/placeholder.svg?height=350&width=300",
    description: "Smooth and elegant silk button-up shirt for a sophisticated look.",
    category: "Shirts",
    images: ["/placeholder.svg?height=350&width=300", "/placeholder.svg?height=350&width=300"],
    sizes: ["S", "M", "L"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Emerald", hex: "#50C878" },
    ],
    material: "100% Silk",
    careInstructions: "Dry clean only.",
    fabric: ["Silk"],
    model3D: "/models/blouse.glb",
  },
  {
    id: "denim-overshirt",
    name: "Denim Overshirt",
    price: 520.0,
    image: "/placeholder.svg?height=350&width=300",
    description: "Versatile denim overshirt, perfect for layering.",
    category: "Shirts",
    images: ["/placeholder.svg?height=350&width=300", "/placeholder.svg?height=350&width=300"],
    sizes: ["M", "L", "XL"],
    colors: [
      { name: "Blue Denim", hex: "#4682B4" },
      { name: "Grey Denim", hex: "#696969" },
    ],
    material: "100% Cotton Denim",
    careInstructions: "Machine wash cold, inside out.",
    fabric: ["Denim"],
    model3D: "/models/jacket.glb",
  },
  {
    id: "flannel-check-shirt",
    name: "Soft Flannel Check Shirt",
    price: 390.0,
    image: "/placeholder.svg?height=350&width=300",
    description: "Warm and soft flannel shirt with a classic check pattern.",
    category: "Shirts",
    images: ["/placeholder.svg?height=350&width=300", "/placeholder.svg?height=350&width=300"],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Red Check", hex: "#FF0000" },
      { name: "Green Check", hex: "#008000" },
    ],
    material: "100% Cotton Flannel",
    careInstructions: "Machine wash warm, tumble dry low.",
    fabric: ["Cotton"],
    model3D: "/models/shirt.glb",
  },
  {
    id: "stretch-performance-shirt",
    name: "Stretch Performance Shirt",
    price: 470.0,
    image: "/placeholder.svg?height=350&width=300",
    description: "Moisture-wicking and stretchable shirt for active lifestyles.",
    category: "Shirts",
    images: ["/placeholder.svg?height=350&width=300", "/placeholder.svg?height=350&width=300"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Navy", hex: "#000080" },
      { name: "Black", hex: "#000000" },
    ],
    material: "90% Polyester, 10% Spandex",
    careInstructions: "Machine wash cold, hang dry.",
    fabric: ["Polyester", "Spandex"],
    model3D: "/models/shirt.glb",
  },
  {
    id: "embroidered-cotton-shirt",
    name: "Embroidered Cotton Shirt",
    price: 510.0,
    image: "/placeholder.svg?height=350&width=300",
    description: "Premium cotton shirt with intricate embroidery details.",
    category: "Shirts",
    images: ["/placeholder.svg?height=350&width=300", "/placeholder.svg?height=350&width=300"],
    sizes: ["S", "M", "L"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Cream", hex: "#F5F5DC" },
    ],
    material: "100% Cotton",
    careInstructions: "Hand wash cold, lay flat to dry.",
    fabric: ["Cotton"],
    model3D: "/models/shirt.glb",
  },
  {
    id: "striped-poplin-shirt",
    name: "Striped Poplin Shirt",
    price: 430.0,
    image: "/placeholder.svg?height=350&width=300",
    description: "Crisp poplin shirt with a classic stripe pattern, perfect for smart casual.",
    category: "Shirts",
    images: ["/placeholder.svg?height=350&width=300", "/placeholder.svg?height=350&width=300"],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Blue Stripe", hex: "#ADD8E6" },
      { name: "Grey Stripe", hex: "#808080" },
    ],
    material: "100% Cotton",
    careInstructions: "Machine wash cold, iron low.",
    fabric: ["Cotton"],
    model3D: "/models/shirt.glb",
  },
  {
    id: "oversized-tunic-shirt",
    name: "Oversized Tunic Shirt",
    price: 490.0,
    image: "/placeholder.svg?height=350&width=300",
    description: "Relaxed fit tunic shirt for a modern, comfortable silhouette.",
    category: "Shirts",
    images: ["/placeholder.svg?height=350&width=300", "/placeholder.svg?height=350&width=300"],
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: "Olive Green", hex: "#808000" },
      { name: "Black", hex: "#000000" },
    ],
    material: "55% Linen, 45% Viscose",
    careInstructions: "Hand wash cold, hang dry.",
    fabric: ["Linen", "Viscose"],
    model3D: "/models/blouse.glb",
  },
  {
    id: "corduroy-shirt",
    name: "Soft Corduroy Shirt",
    price: 460.0,
    image: "/placeholder.svg?height=350&width=300",
    description: "Warm and textured corduroy shirt, great for autumn and winter.",
    category: "Shirts",
    images: ["/placeholder.svg?height=350&width=300", "/placeholder.svg?height=350&width=300"],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Brown", hex: "#A52A2A" },
      { name: "Navy", hex: "#000080" },
    ],
    material: "100% Cotton Corduroy",
    careInstructions: "Machine wash cold, tumble dry low.",
    fabric: ["Cotton"],
    model3D: "/models/shirt.glb",
  },

  // Trousers Products (10 products)
  {
    id: "classic-wool-trousers",
    name: "Classic Wool Trousers",
    price: 580.0,
    image: "/placeholder.svg?height=400&width=300",
    description: "Tailored wool trousers for a sharp and sophisticated look.",
    category: "Trousers",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    sizes: ["28", "30", "32", "34", "36"],
    colors: [
      { name: "Charcoal", hex: "#36454F" },
      { name: "Navy", hex: "#000080" },
    ],
    material: "100% Wool",
    careInstructions: "Dry clean only.",
    fabric: ["Wool"],
    model3D: "/models/trousers.glb",
  },
  {
    id: "stretch-chino-trousers",
    name: "Stretch Chino Trousers",
    price: 420.0,
    image: "/placeholder.svg?height=400&width=300",
    description: "Comfortable stretch chinos, perfect for everyday wear.",
    category: "Trousers",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    sizes: ["28", "30", "32", "34", "36"],
    colors: [
      { name: "Khaki", hex: "#C3B091" },
      { name: "Black", hex: "#000000" },
    ],
    material: "97% Cotton, 3% Spandex",
    careInstructions: "Machine wash cold, iron low.",
    fabric: ["Cotton", "Spandex"],
    model3D: "/models/trousers.glb",
  },
  {
    id: "wide-leg-linen-trousers",
    name: "Wide-Leg Linen Trousers",
    price: 490.0,
    image: "/placeholder.svg?height=400&width=300",
    description: "Flowy wide-leg linen trousers for a relaxed yet elegant style.",
    category: "Trousers",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Olive", hex: "#808000" },
    ],
    material: "100% Linen",
    careInstructions: "Machine wash cold, gentle cycle.",
    fabric: ["Linen"],
    model3D: "/models/trousers.glb",
  },
  {
    id: "pleated-dress-trousers",
    name: "Pleated Dress Trousers",
    price: 550.0,
    image: "/placeholder.svg?height=400&width=300",
    description: "Classic pleated trousers, ideal for formal occasions or business wear.",
    category: "Trousers",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    sizes: ["28", "30", "32", "34", "36"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Grey", hex: "#808080" },
    ],
    material: "65% Polyester, 35% Viscose",
    careInstructions: "Dry clean recommended.",
    fabric: ["Polyester", "Viscose"],
    model3D: "/models/trousers.glb",
  },
  {
    id: "jogger-style-trousers",
    name: "Jogger Style Trousers",
    price: 380.0,
    image: "/placeholder.svg?height=400&width=300",
    description: "Comfortable jogger-style trousers with a modern tapered fit.",
    category: "Trousers",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Navy", hex: "#000080" },
      { name: "Charcoal", hex: "#36454F" },
    ],
    material: "80% Cotton, 20% Polyester",
    careInstructions: "Machine wash cold, tumble dry low.",
    fabric: ["Cotton", "Polyester"],
    model3D: "/models/trousers.glb",
  },
  {
    id: "velvet-trousers",
    name: "Velvet Slim Fit Trousers",
    price: 650.0,
    image: "/placeholder.svg?height=400&width=300",
    description: "Luxurious velvet trousers for a sophisticated evening look.",
    category: "Trousers",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    sizes: ["28", "30", "32", "34"],
    colors: [
      { name: "Burgundy", hex: "#800020" },
      { name: "Forest Green", hex: "#228B22" },
    ],
    material: "95% Polyester, 5% Spandex Velvet",
    careInstructions: "Dry clean only.",
    fabric: ["Velvet", "Polyester", "Spandex"],
    model3D: "/models/trousers.glb",
  },
  {
    id: "cropped-trousers",
    name: "Cropped Tailored Trousers",
    price: 470.0,
    image: "/placeholder.svg?height=400&width=300",
    description: "Stylish cropped trousers with a modern tailored fit.",
    category: "Trousers",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Navy", hex: "#000080" },
    ],
    material: "60% Polyester, 35% Viscose, 5% Elastane",
    careInstructions: "Machine wash cold, hang dry.",
    fabric: ["Polyester", "Viscose", "Elastane"],
    model3D: "/models/trousers.glb",
  },
  {
    id: "cargo-trousers",
    name: "Utility Cargo Trousers",
    price: 440.0,
    image: "/placeholder.svg?height=400&width=300",
    description: "Durable cargo trousers with multiple pockets for a utilitarian style.",
    category: "Trousers",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Olive Green", hex: "#808000" },
      { name: "Khaki", hex: "#C3B091" },
    ],
    material: "100% Cotton Twill",
    careInstructions: "Machine wash warm, tumble dry low.",
    fabric: ["Cotton"],
    model3D: "/models/trousers.glb",
  },
  {
    id: "leather-trousers",
    name: "Faux Leather Trousers",
    price: 590.0,
    image: "/placeholder.svg?height=400&width=300",
    description: "Edgy faux leather trousers for a bold fashion statement.",
    category: "Trousers",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    sizes: ["XS", "S", "M", "L"],
    colors: [{ name: "Black", hex: "#000000" }],
    material: "100% Polyurethane (Faux Leather)",
    careInstructions: "Wipe clean with damp cloth.",
    fabric: ["Faux Leather"],
    model3D: "/models/trousers.glb",
  },
  {
    id: "track-trousers",
    name: "Sporty Track Trousers",
    price: 360.0,
    image: "/placeholder.svg?height=400&width=300",
    description: "Comfortable and stylish track trousers for athletic or casual wear.",
    category: "Trousers",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Grey", hex: "#808080" },
    ],
    material: "100% Polyester",
    careInstructions: "Machine wash cold, tumble dry low.",
    fabric: ["Polyester"],
    model3D: "/models/trousers.glb",
  },

  // Suits Products (10 products)
  {
    id: "classic-two-piece-suit",
    name: "Classic Two-Piece Suit",
    price: 1200.0,
    image: "/placeholder.svg?height=450&width=350",
    description: "A timeless two-piece suit, perfect for business or formal events.",
    category: "Suits",
    images: ["/placeholder.svg?height=450&width=350", "/placeholder.svg?height=450&width=350"],
    sizes: ["38R", "40R", "42R", "44R"],
    colors: [
      { name: "Navy", hex: "#000080" },
      { name: "Charcoal", hex: "#36454F" },
    ],
    material: "100% Wool",
    careInstructions: "Dry clean only.",
    fabric: ["Wool"],
    model3D: "/models/suit.glb",
  },
  {
    id: "slim-fit-tuxedo",
    name: "Slim Fit Tuxedo",
    price: 1500.0,
    image: "/placeholder.svg?height=450&width=350",
    description: "Elegant slim-fit tuxedo for black-tie events.",
    category: "Suits",
    images: ["/placeholder.svg?height=450&width=350", "/placeholder.svg?height=450&width=350"],
    sizes: ["38S", "40S", "42S", "44S"],
    colors: [{ name: "Black", hex: "#000000" }],
    material: "Wool Blend with Satin Lapels",
    careInstructions: "Dry clean only.",
    fabric: ["Wool", "Satin"],
    model3D: "/models/suit.glb",
  },
  {
    id: "linen-summer-suit",
    name: "Linen Summer Suit",
    price: 1100.0,
    image: "/placeholder.svg?height=450&width=350",
    description: "Lightweight linen suit, perfect for warm-weather formal occasions.",
    category: "Suits",
    images: ["/placeholder.svg?height=450&width=350", "/placeholder.svg?height=450&width=350"],
    sizes: ["36R", "38R", "40R", "42R"],
    colors: [
      { name: "Light Grey", hex: "#D3D3D3" },
      { name: "Beige", hex: "#F5F5DC" },
    ],
    material: "100% Linen",
    careInstructions: "Dry clean only.",
    fabric: ["Linen"],
    model3D: "/models/suit.glb",
  },
  {
    id: "velvet-blazer",
    name: "Velvet Dinner Blazer",
    price: 750.0,
    image: "/placeholder.svg?height=400&width=350",
    description: "Luxurious velvet blazer, ideal for adding a touch of elegance to any outfit.",
    category: "Suits",
    images: ["/placeholder.svg?height=400&width=350", "/placeholder.svg?height=400&width=350"],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Burgundy", hex: "#800020" },
      { name: "Navy", hex: "#000080" },
    ],
    material: "100% Polyester Velvet",
    careInstructions: "Dry clean only.",
    fabric: ["Velvet", "Polyester"],
    model3D: "/models/blazer.glb",
  },
  {
    id: "checked-suit",
    name: "Modern Checked Suit",
    price: 1350.0,
    image: "/placeholder.svg?height=450&width=350",
    description: "Stylish checked suit for a contemporary and bold statement.",
    category: "Suits",
    images: ["/placeholder.svg?height=450&width=350", "/placeholder.svg?height=450&width=350"],
    sizes: ["38R", "40R", "42R", "44R"],
    colors: [
      { name: "Grey Check", hex: "#808080" },
      { name: "Blue Check", hex: "#4682B4" },
    ],
    material: "Wool Blend",
    careInstructions: "Dry clean only.",
    fabric: ["Wool", "Polyester"],
    model3D: "/models/suit.glb",
  },
  {
    id: "three-piece-suit",
    name: "Three-Piece Formal Suit",
    price: 1600.0,
    image: "/placeholder.svg?height=450&width=350",
    description: "Complete three-piece suit for ultimate formal elegance.",
    category: "Suits",
    images: ["/placeholder.svg?height=450&width=350", "/placeholder.svg?height=450&width=350"],
    sizes: ["40R", "42R", "44R", "46R"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Navy", hex: "#000080" },
    ],
    material: "100% Super 120s Wool",
    careInstructions: "Dry clean only.",
    fabric: ["Wool"],
    model3D: "/models/suit.glb",
  },
  {
    id: "seersucker-suit",
    name: "Seersucker Summer Suit",
    price: 1050.0,
    image: "/placeholder.svg?height=450&width=350",
    description: "Light and breathable seersucker suit, perfect for summer events.",
    category: "Suits",
    images: ["/placeholder.svg?height=450&width=350", "/placeholder.svg?height=450&width=350"],
    sizes: ["36R", "38R", "40R", "42R"],
    colors: [{ name: "Blue Stripe", hex: "#ADD8E6" }],
    material: "100% Cotton Seersucker",
    careInstructions: "Dry clean only.",
    fabric: ["Cotton"],
    model3D: "/models/suit.glb",
  },
  {
    id: "corduroy-suit",
    name: "Corduroy Casual Suit",
    price: 1150.0,
    image: "/placeholder.svg?height=450&width=350",
    description: "Relaxed corduroy suit for a smart casual or vintage-inspired look.",
    category: "Suits",
    images: ["/placeholder.svg?height=450&width=350", "/placeholder.svg?height=450&width=350"],
    sizes: ["38R", "40R", "42R", "44R"],
    colors: [
      { name: "Brown", hex: "#A52A2A" },
      { name: "Forest Green", hex: "#228B22" },
    ],
    material: "100% Cotton Corduroy",
    careInstructions: "Dry clean only.",
    fabric: ["Cotton"],
    model3D: "/models/suit.glb",
  },
  {
    id: "double-breasted-suit",
    name: "Double-Breasted Power Suit",
    price: 1450.0,
    image: "/placeholder.svg?height=450&width=350",
    description: "Bold double-breasted suit for a commanding presence.",
    category: "Suits",
    images: ["/placeholder.svg?height=450&width=350", "/placeholder.svg?height=450&width=350"],
    sizes: ["40R", "42R", "44R", "46R"],
    colors: [
      { name: "Navy Pinstripe", hex: "#000080" },
      { name: "Grey", hex: "#808080" },
    ],
    material: "Wool Blend",
    careInstructions: "Dry clean only.",
    fabric: ["Wool", "Polyester"],
    model3D: "/models/suit.glb",
  },
  {
    id: "travel-suit",
    name: "Wrinkle-Resistant Travel Suit",
    price: 1300.0,
    image: "/placeholder.svg?height=450&width=350",
    description: "Performance suit designed to resist wrinkles, perfect for travel.",
    category: "Suits",
    images: ["/placeholder.svg?height=450&width=350", "/placeholder.svg?height=450&width=350"],
    sizes: ["38R", "40R", "42R", "44R"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Blue", hex: "#0000FF" },
    ],
    material: "100% High-Performance Polyester",
    careInstructions: "Machine wash cold, hang dry.",
    fabric: ["Polyester"],
    model3D: "/models/suit.glb",
  },

  // Accessories Products (10 products)
  {
    id: "silk-pocket-square",
    name: "Silk Pocket Square",
    price: 80.0,
    image: "/placeholder.svg?height=200&width=200",
    description: "A luxurious silk pocket square to complete your formal attire.",
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=200", "/placeholder.svg?height=200&width=200"],
    sizes: ["One Size"],
    colors: [
      { name: "Red", hex: "#FF0000" },
      { name: "Blue", hex: "#0000FF" },
      { name: "Gold", hex: "#FFD700" },
    ],
    material: "100% Silk",
    careInstructions: "Dry clean only.",
    fabric: ["Silk"],
    model3D: "/models/pocket-square.glb",
  },
  {
    id: "leather-belt",
    name: "Genuine Leather Belt",
    price: 150.0,
    image: "/placeholder.svg?height=200&width=300",
    description: "High-quality genuine leather belt for durability and style.",
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=300", "/placeholder.svg?height=200&width=300"],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Brown", hex: "#A52A2A" },
    ],
    material: "100% Cowhide Leather",
    careInstructions: "Wipe clean with leather conditioner.",
    fabric: ["Leather"],
    model3D: "/models/belt.glb",
  },
  {
    id: "cashmere-scarf",
    name: "Soft Cashmere Scarf",
    price: 250.0,
    image: "/placeholder.svg?height=250&width=250",
    description: "Luxuriously soft cashmere scarf for warmth and elegance.",
    category: "Accessories",
    images: ["/placeholder.svg?height=250&width=250", "/placeholder.svg?height=250&width=250"],
    sizes: ["One Size"],
    colors: [
      { name: "Grey", hex: "#808080" },
      { name: "Navy", hex: "#000080" },
    ],
    material: "100% Cashmere",
    careInstructions: "Dry clean only.",
    fabric: ["Cashmere"],
    model3D: "/models/scarf.glb",
  },
  {
    id: "minimalist-watch",
    name: "Minimalist Wrist Watch",
    price: 300.0,
    image: "/placeholder.svg?height=200&width=200",
    description: "Sleek and modern watch with a minimalist design.",
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=200", "/placeholder.svg?height=200&width=200"],
    sizes: ["One Size"],
    colors: [
      { name: "Silver", hex: "#C0C0C0" },
      { name: "Gold", hex: "#FFD700" },
    ],
    material: "Stainless Steel, Leather Strap",
    careInstructions: "Wipe clean with soft cloth.",
    fabric: ["Leather", "Metal"],
    model3D: "/models/watch.glb",
  },
  {
    id: "classic-tie",
    name: "Classic Silk Tie",
    price: 90.0,
    image: "/placeholder.svg?height=200&width=200",
    description: "A classic silk tie, essential for formal and business attire.",
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=200", "/placeholder.svg?height=200&width=200"],
    sizes: ["One Size"],
    colors: [
      { name: "Navy", hex: "#000080" },
      { name: "Red", hex: "#FF0000" },
    ],
    material: "100% Silk",
    careInstructions: "Dry clean only.",
    fabric: ["Silk"],
    model3D: "/models/tie.glb",
  },
  {
    id: "leather-wallet",
    name: "Premium Leather Wallet",
    price: 180.0,
    image: "/placeholder.svg?height=200&width=250",
    description: "Handcrafted leather wallet with multiple card slots.",
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=250", "/placeholder.svg?height=200&width=250"],
    sizes: ["One Size"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Brown", hex: "#A52A2A" },
    ],
    material: "Genuine Leather",
    careInstructions: "Wipe clean with leather conditioner.",
    fabric: ["Leather"],
    model3D: "/models/wallet.glb",
  },
  {
    id: "sunglasses",
    name: "Classic Aviator Sunglasses",
    price: 220.0,
    image: "/placeholder.svg?height=200&width=300",
    description: "Timeless aviator sunglasses with UV protection.",
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=300", "/placeholder.svg?height=200&width=300"],
    sizes: ["One Size"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Gold Frame", hex: "#FFD700" },
    ],
    material: "Metal Frame, Polycarbonate Lenses",
    careInstructions: "Wipe clean with soft cloth.",
    fabric: ["Metal", "Plastic"],
    model3D: "/models/sunglasses.glb",
  },
  {
    id: "cufflinks",
    name: "Elegant Cufflinks",
    price: 120.0,
    image: "/placeholder.svg?height=150&width=150",
    description: "Sophisticated cufflinks to add a refined touch to your shirt.",
    category: "Accessories",
    images: ["/placeholder.svg?height=150&width=150", "/placeholder.svg?height=150&width=150"],
    sizes: ["One Size"],
    colors: [
      { name: "Silver", hex: "#C0C0C0" },
      { name: "Gold", hex: "#FFD700" },
    ],
    material: "Stainless Steel",
    careInstructions: "Wipe clean with soft cloth.",
    fabric: ["Metal"],
    model3D: "/models/cufflinks.glb",
  },
  {
    id: "beanie",
    name: "Knitted Beanie",
    price: 70.0,
    image: "/placeholder.svg?height=200&width=200",
    description: "Warm and stylish knitted beanie for cooler weather.",
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=200", "/placeholder.svg?height=200&width=200"],
    sizes: ["One Size"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Navy", hex: "#000080" },
    ],
    material: "100% Acrylic",
    careInstructions: "Hand wash cold, lay flat to dry.",
    fabric: ["Acrylic"],
    model3D: "/models/beanie.glb",
  },
  {
    id: "gloves",
    name: "Leather Driving Gloves",
    price: 190.0,
    image: "/placeholder.svg?height=200&width=250",
    description: "Stylish leather driving gloves for comfort and grip.",
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=250", "/placeholder.svg?height=200&width=250"],
    sizes: ["S", "M", "L"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Brown", hex: "#A52A2A" },
    ],
    material: "Genuine Leather",
    careInstructions: "Professional leather clean only.",
    fabric: ["Leather"],
    model3D: "/models/gloves.glb",
  },
]

export const getProductsByCategory = (category: Product["category"]) => {
  return allProducts.filter((product) => product.category === category)
}
